export enum SignInErrorCode {
  SIGN_IN_USER_NOT_FOUND = 'SIGN_IN_USER_NOT_FOUND',
  SIGN_IN_INCORRECT_PASSWORD = 'SIGN_IN_INCORRECT_PASSWORD'
}

export enum SignUpErrorCode {
  SIGN_UP_USER_ALREADY_EXISTS = 'SIGN_UP_USER_ALREADY_EXISTS'
}
